name: Run Tests

on: [workflow_dispatch]
#  workflow_dispatch:
#    branches: [unit-tests]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: ctests
      run: ctest
